lsc-project/lsc

bin/lsc-agent.bat
sample/hsqldb/bin/lsc-sample.bat

The goal is to fix the sample on Windows

Replace # by REM in bat scripts (references #9)

---

etc/lsc.xml-sample

LSC sample file installed under /etc/lsc contains a call to a non existing function.

Fixed non existing function called in sample lsc xml file

---

bin/hsqldb

Add option to force HSQLDB to listen on localhost
References #96

Force HSQLDB to listen on localhost

---

src/install/lsc-core.spec

Create LSC group and user as system

---

src/main/java/org/lsc/service/AbstractJdbcDstService.java

Enhancement for #69 Fix Null pointer thrown in job containing multiple tasks with database destinations and sync options.

---

src/main/java/org/lsc/jndi/JndiServices.java

This PR fixes the NullPointerException that is is thrown when an empty context DN is set in a LDAP connection URL.
Follows up PR #116 whose proposed fix was more complex and sent on the wrong branch (master).

Fix: avoid NullPointerException on empty context DN

---

.travis.yml
README.md

hoping correctly rebased this time

Advertise and use Libera Chat for irc (#201)

---

src/main/java/org/lsc/SimpleSynchronize.java
src/test/java/org/lsc/Ldap2LdapOrderedSyncTest.java
src/test/resources/etc/lsc.xml

See #67, and especially https://github.com/lsc-project/lsc/issues/67#issuecomment-1597310928

enforce order of user-defined tasks at launch

---

src/main/java/org/lsc/AbstractSynchronize.java
src/main/java/org/lsc/SimpleSynchronize.java
src/main/java/org/lsc/SynchronizeThreadPoolExecutor.java
src/main/java/org/lsc/beans/InfoCounter.java
src/main/java/org/lsc/runnable/AbstractEntryRunner.java
src/main/java/org/lsc/runnable/AsynchronousRunner.java
src/main/java/org/lsc/runnable/CleanEntryRunner.java
src/main/java/org/lsc/runnable/SynchronizeEntryRunner.java

- Use multithreading for clean phase using --thread parameter (#108)
- Refactored AbstractSynchronize (removed inner classes)
- Fixed ident

Use multithreading for clean phase using --thread parameter (#108)

---

src/install/debian/changelog
src/install/debian/control
src/install/debian/lsc.install
src/install/debian/lsc.manpages
src/install/debian/lsc.postinst
src/install/debian/lsc.preinst
src/install/debian/nagios-plugins-lsc.install
src/install/debian/rules

deb cleanup (#264)

---

src/test/resources/etc/lsc.xml

remove explicit `js:` engine in tests (#275)

---

sample/hsqldb/bin/lsc-sample
sample/ldap2hsqldb/bin/lsc-sample

fix: sample code doesn't run from Debian package

---

BUILD.txt
src/main/java/org/lsc/AbstractSynchronize.java

As discussed here: https://mail.ow2.org/wws/arc/lsc-users/2024-07/msg00006.html
Based on the pull request that can't be pulled anymore: https://github.com/lsc-project/lsc/pull/53
It builds, but I can't find out how to run the freshly made lsc. It complains about a manifest:
```
➜ java -jar target/lsc-core-2.2-SNAPSHOT.jar 
no main manifest attribute, in target/lsc-core-2.2-SNAPSHOT.jar
```
I left out modifications to the perl file as I can't test the code.

Log task name+mode as well

---

pom.xml

#106 updating dependencies

---

pom.xml

add jaxb-API specific dependencies for jdk11+ (#317)

---

pom.xml

Force surefire test provider to junit4, to detect tests again (#319)

---

pom.xml

fix slow performance on graalvm with jdk11 (#322)

---

bin/lsc
pom.xml
src/main/java/org/lsc/utils/ScriptingEvaluator.java

fix graalvm usage on jdk 11, 17, 21 (#340)

---

.github/workflows/maven.yml
pom.xml

make github unit tests run in parallel + fix build for jdk 21 (#346)

---

bin/lsc
pom.xml
src/install/debian/lsc.install
src/install/debian/rules
src/install/lsc.spec
src/main/assembly/dist.xml

package graalvm dependencies (#287)

---

etc/logback.xml
sample/ad/etc-ad2opendj/logback.xml
sample/ad/etc-opendj2ad/logback.xml
sample/asyncldap/etc-opendj2openldap/logback.xml
sample/asyncldap/etc-openldap2opendj/logback.xml
sample/hsqldb/etc/logback-opends.xml
sample/hsqldb/etc/logback.xml
sample/ldap2hsqldb/etc/logback-opends.xml
sample/ldap2hsqldb/etc/logback.xml
sample/multi/etc/logback.xml
sample/nis/etc/logback-opends.xml
sample/nis/etc/logback.xml
sample/postgresql/etc-opendj2postgresql/logback.xml
sample/postgresql/etc-postgresql2opendj/logback.xml
src/main/java/org/lsc/utils/output/CsvLayout.java
src/main/java/org/lsc/utils/output/LdifLayout.java
src/test/java/org/lsc/utils/output/CsvLayoutTest.java

Cleanup the CSV and LDIF layouts for logback feature

---

src/main/java/org/lsc/utils/ScriptingEvaluator.java
src/test/java/org/lsc/utils/ScriptingEvaluatorTest.java

improve jscript prefix identifier and test the graalvm loading (#360)

---

LICENSE.txt
NOTICE.txt

Updated the LICENSE file, added the NOTICE file (#328)

---

src/main/java/org/lsc/beans/LscBean.java
src/main/java/org/lsc/connectors/xmlrpc/AbstractLscXmlRpcObject.java
src/main/java/org/lsc/jndi/AbstractSimpleJndiService.java
src/main/java/org/lsc/jndi/ActiveDirectoryDstService.java
src/main/java/org/lsc/jndi/JndiModifications.java
src/main/java/org/lsc/jndi/JndiServices.java
src/main/java/org/lsc/utils/SetUtils.java

Closing all NamingEnumeration when they are not anymore in use (#363)

---

src/main/java/org/lsc/jndi/JndiServices.java

Closes #350 
o Merged the two controls addition into one operation 
o Removed the private sortedBy field, it has no reason to exist 
o Minor code reformating
o Removed \t at the end of lines

The JndiServices.contextRequestControls method can be simplified #350

---

src/main/java/org/lsc/SimpleSynchronize.java
src/test/java/org/lsc/jmx/LscJmxTest.java

Fix SimpleSynchronize init() method can be quite slow (#332)

---

src/install/lsc.spec

fix postinst script warning during RPM install (#372)

---

etc/logback.xml
sample/ad/etc-ad2opendj/logback.xml
sample/ad/etc-opendj2ad/logback.xml
sample/asyncldap/etc-opendj2openldap/logback.xml
sample/asyncldap/etc-openldap2opendj/logback.xml
sample/hsqldb/etc/logback-opends.xml
sample/hsqldb/etc/logback.xml
sample/ldap2hsqldb/etc/logback-opends.xml
sample/ldap2hsqldb/etc/logback.xml
sample/multi/etc/logback.xml
sample/nis/etc/logback-opends.xml
sample/nis/etc/logback.xml
sample/postgresql/etc-opendj2postgresql/logback.xml
sample/postgresql/etc-postgresql2opendj/logback.xml
src/install/debian/rules
src/install/lsc.spec
src/main/resources/logback.xml
src/test/resources/etc/logback-opends.xml
src/test/resources/etc/logback.xml

370 logback issues

---

bin/lsc
pom.xml
sample/hsqldb/bin/lsc-sample
sample/hsqldb/etc/logback-opends.xml
sample/ldap2hsqldb/bin/lsc-sample
sample/ldap2hsqldb/etc/logback-opends.xml

remove OpenDJ profile, but keep opendj embedded server for sample scripts (#355)

---

sample/hsqldb/bin/lsc-sample
sample/ldap2hsqldb/bin/lsc-sample
sample/ldap2hsqldb/etc/lsc.xml
sample/ldap2hsqldb/etc/test.ldif
src/install/debian/rules
src/install/lsc.spec

fix hsqldb and ldap2hsqldb sample scripts (#388)

---

src/main/java/org/lsc/jndi/JndiServices.java

Fix the controls addition (#375)

---

sample/hsqldb/sample.csv
sample/ldap2hsqldb/etc/test.ldif
src/test/java/org/lsc/db2ldap/Jdbc2LdapSyncTest.java

Do not use real email addresses

Use better sample data

---

src/install/debian/lsc.install
src/install/lsc.spec

do not copy systemd files into /usr/lib/lsc (#393)

---

src/main/java/org/lsc/beans/BeanComparator.java

fix wrong order of operations for multi-valued attributes (#401)

---

src/install/debian/lsc.postinst
src/install/lsc.spec

Upgrade home directory of lsc user set by previous lsc versions (#399)

---

pom.xml
src/main/java/org/lsc/Launcher.java

fix version option (#403)

---

src/main/java/org/lsc/Configuration.java
src/main/java/org/lsc/Launcher.java

Ajout du message d'erreur contennt la ligne et la colonne quand le fichier de configuration est incorrecte

Fix pour issue 416
