- src/main/java/org/lsc/AbstractSynchronize.java
- src/main/java/org/lsc/SynchronizeThreadPoolExecutor.java
Fixes out of memory error by changing the way large thead executor pool's queue fills up when running large amount of sync entries. This proposed solution uses a rejectedExecution handler, instead of terminating threads 15 minutes after shutdown signal was sent. When adding a new thread to an already full queue, the run command will wait until there is space available in the queue for the new thread.
Fixes http://tools.lsc-project.org/issues/862
Fixes http://tools.lsc-project.org/issues/748
Related to http://tools.lsc-project.org/issues/742
Originally discussed in https://lists.lsc-project.org/pipermail/lsc-users/2013-August/001584.html
Credit : http://stackoverflow.com/a/10353250/7436404
> Prevent thead executor pool's queue to saturate when running large amount of sync entries

- pom.xml
Switching to forgerock ce repository for opendj dependency, after a forgerock changed its access policy to http://maven.forgerock.org/repo/releases repository.
> Switching to forgerock ce opendj

- sample/hsqldb/etc/test.ldif
Running the sample example triggers an error if no structural objectClass is provided in the LDIF file:
$ bin/lsc-sample --start-ldap-server
Starting LDAP server on ldap://localhost:33389/ ...
juin 27 14:34:40 - INFO  - Logging configuration successfully loaded from /home/johndoe/lsc/sample/hsqldb/bin/../etc/logback.xml 
juin 27 14:34:40 - INFO  - LSC configuration successfully loaded from /home/johndoe/lsc/sample/hsqldb/bin/../etc/
6205 [main] ERROR org.lsc.opendj.LdapServer - org.opends.server.util.LDIFException: Entry dc=lsc-project,dc=org read from LDIF starting at line 1 is not valid because it violates the server's schema configuration:  Entry dc=lsc-project,dc=org violates the Directory Server schema configuration because it does not include a structural objectclass.  All entries …
> add a structural objectClass to hsqldb sample root dn

- .travis.yml
- src/main/java/org/lsc/service/SyncReplSourceService.java
This fix re-connect to LDAP during async tasks if connection has timed out.
Currently, task connection is kept forever while running async check, potentially leading to lost connection errors after some times as it is only used when changes are detected :
* Lost connection error :
java.io.IOException: Connection reset by peer
at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[na:1.8.0_151]
at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[na:1.8.0_151]
at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[na:1.8.0_151]
at sun.nio.ch.IOUtil.read(IOUtil.java:197) ~[na:1.8.0_151]
at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[na:1.8.0_151]
at org.apache.mina.transport.socket.nio.NioProcessor.read(NioProcessor.java:273) ~[mina-core-2.0.7.jar:na] …
> Fix #40 async task connection reset after 15 minutes & fix travis

- src/main/java/org/lsc/jndi/ScriptableJndiServices.java
Hello,
**Context** 
I'm using LSC to synchronize a LDAP eDirectory to a LDAP OpenDj.
The directories (source - target) haven't got the same structure.  So I had to write some javascript to build members attributes in my destination directory.
During tests, I faced performances issues with thousands source entries. 
Because my Javascript searched Dn with srcLdap.search queries and then for each dn searched a unique attribute value using  srcLdap.attribute.
**LSC changes**
I understood that if I can search directly unique attribute values using a new method  srcLdap.searchAttribute, performances will be improved.
So I developped new ScriptableJNDI services :
-searchAttribute : Performs a search with subtree scope on a given base DN with a given filter that returns attribute values. …
> Javascript feature to search attribute values

- src/main/java/org/lsc/configuration/JaxbXmlConfigurationHelper.java
Configuring multiple plugin packages e.g
-DLSC.PLUGINS.PACKAGEPATH=foo.bar.plugins.configuration.file:foo.bar.plugins.configuration.ext
fails on Windows.
Fixes #62
> Fix Issue #62:

- .travis.yml
Travis build currently fails :
```
Installing oraclejdk8
$ export JAVA_HOME=~/oraclejdk8
$ export PATH="$JAVA_HOME/bin:$PATH"
$ ~/bin/install-jdk.sh --target "/home/travis/oraclejdk8" --workspace "/home/travis/.cache/install-jdk" --feature "8" --license "BCL"
install-jdk.sh 2019-05-02
Expected feature release number in range of 9 to 14, but got: 8
The command "~/bin/install-jdk.sh --target "/home/travis/oraclejdk8" --workspace "/home/travis/.cache/install-jdk" --feature "8" --license "BCL"" failed and exited with 3 during .
Your build has been stopped.
```
This is PR attempt to restore build using openjdk8 instead of oraclejdk8.
> Fix travis build: switching to openjdk8

- src/main/java/org/lsc/configuration/JaxbXmlConfigurationHelper.java
- src/main/java/org/lsc/configuration/XsdForLscComparator.java
- src/test/java/org/lsc/configuration/XsdForLscComparatorTest.java
For the moment the list of xsd files is loaded in the reverse order of  their hash.
so `lsc-openpaas-plugin-1.0.xsd` will be loaded after `schemas/lsc-core-2.1.xsd`
but  `lsc-james-plugin-1.0.xsd` will be loaded before and the call to ` schemaFactory.newSchema` will fail with a `SAXException` as the definitions in lsc core are required in the plugin schema.
The hash is not easily determinable and is an implementation details which is not desirable.
For example `lsc-james0-plugin-1.0.xsd`  is loaded in the correct order but is not `lsc-james-plugin-1.0.xsd`.
There is also a risk to change the order of the hashes of the core and the plugin by incrementing the version of the files.
This proposal aims to always load the core xsd first then the others in alphabetical order.
> sort xsd files list

- src/test/java/org/lsc/utils/directory/LDAPTest.java
`no.such.host` unfortunately is now a real address. It makes a test uselessly slow.
> Replace existing address no.such.host by a non existing one (for now?)

- .travis.yml
- pom.xml
- src/main/java/org/lsc/utils/JScriptEvaluator.java
The goal of this pull request is to make LSC (future 2.2 version) compatible with only supported Java version: 8 et 11.
> Make LSC compatible with JDK 11, remove compatibility with JDK 5, 6, 7

- pom.xml
This PR restores the javadoc.opts property in pom.xml used for build with JVMs in version 8+ that was lost after  support for Java 11 was added.
It prevents maven build to fail with this error: 
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 8:33.389s
[INFO] Finished at: Tue Jan 14 10:25:58 CET 2020
[INFO] Final Memory: 39M/60M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.8:javadoc (default) on project lsc-core: An error has occurred in JavaDocs report generation:
[ERROR] Exit code: 1 - javadoc: warning - Multiple sources …
```
> Fixed javadoc generator warning error when building with maven

- src/main/java/org/lsc/jndi/JndiServices.java
Error message is misleading as the faulty connection could also be the source connection.
Since we don't know which connection is opened, this PR display the connection name and URL for easier debugging.
> Fixed: Wrong error message is displayed #137

- src/main/java/org/lsc/configuration/JaxbXmlConfigurationHelper.java
Found issues #62 and #65 where the separator was made consistent but the chosen separator 'System.getProperty("path.separator")' does not work on Windows.
The separator must be a colon. On Windows the "path.separator" is a semi colon.
> Fix package path calculation and use always colon as separator even on Windows.

- pom.xml
- src/main/java/org/lsc/jndi/JndiServices.java
- src/main/java/org/lsc/service/SyncReplSourceService.java
Hello,
I found a bug working in asynchronous mode with a Novell Edirectory source.
Error is Unexpected DecoderException: The length of controls must not be null.
This bug is known on apache.directory.api (https://issues.apache.org/jira/browse/DIRAPI-295) and has been fixed in 1.0.0 version of org.apache.directory.api api-all.
So I decide to update api-all from 1.0.0-M22 to 1.0.0.
There is an impact in JndiServices and SyncReplSourceService classes. And the project has to run in JAVA 1.8.
Do you think this fix could be integrated to new lsc version ?
Thanks,
Florian
> Fix on asynchronous mode with a Novell Edirectory source

- pom.xml
- src/main/java/org/lsc/utils/ScriptingEvaluator.java
- from java 11 add graaljs supported by graalvm.
- graalvm 22.2.0
- default implementation when no scripting language is provided
- graalsjs has full access to java code and work in nashorn compatibility
- use 'gj' to explictly require graaljs ( and not gr that is groovy ).
- bump rhino to 1.7.14.
> javascript graaljs support and rhino update

- src/main/java/org/lsc/utils/ScriptingEvaluator.java
A script engine (e.g. "Oracle Nashorn") is incorrectly reported as unsupported in debug log message.
If we take as an example the "Oracle Nashorn" script engine, it has the following short names: nashorn, Nashorn, js, JS, JavaScript, javascript, ECMAScript, ecmascript.
With the current implementation, the script engine will be, by default, considered to be supported and if, while iterating on the list of short names, a short name is *not one of*: js, groovy, grall.js, the engine will be considered to be *not supported*. So with the example of "Oracle Nashorn" it will be reported as not supported event if one of its short name is `js` and it is actually loaded (the issue is only related to the log message).
This commit revert the logic: a script engine is by default unsupported and if one …
> Fix inaccurate log message when loading script engine

- pom.xml
According to documentation (`mvn help:describe -Dplugin=org.apache.maven.plugins:maven-javadoc-plugin:3.4.1 -Ddetail | grep additionalparam`), `additionalparam` is not a valid configuration parameter for `maven-javadoc-plugin`. This commit replace`additionalparam`  with `doclint`:
Specifies specific checks to be performed on Javadoc comments.
See [doclint](https://docs.oracle.com/javase/8/docs/technotes/tools/windows/javadoc.html#BEJEFABE).
> Fix maven-javadoc-plugin configuration

- pom.xml
`maven-resources-plugin` is using `project.build.sourceEncoding` to specify encoding to use when copying filtered resources (see https://maven.apache.org/plugins/maven-resources-plugin/examples/encoding.html). `.properties` files are encoded in `ISO-8859-1` (see [Java 8 API documentation](https://docs.oracle.com/javase/8/docs/api/java/util/Properties.html), note that by default, since Java 9, Java runtime try to [read properties file as `UTF-8` encoded](https://docs.oracle.com/en/java/javase/11/intl/internationalization-enhancements1.html#GUID-974CF488-23E8-4963-A322-82006A7A14C7) en fallback to `ISO-8859-1` if needed). To prevent issue, `maven-resources-plugin` log a warning if encoding for `.properties` files is not specified in plugin configuration (see …
> Specify encoding to use for .properties files

- .github/workflows/maven.yml
- README.md
> Add github action

- src/main/java/org/lsc/utils/directory/AD.java
- src/test/java/org/lsc/utils/directory/ADTest.java
…bute from AD to a UUID string representation #43
> Added utility method + unit test to convert a byte[] objectGUID attribute

- pom.xml
During the build I got the following error:
```
Could not transfer artifact org.forgerock.ce.opendj:opendj-server:pom:2.6.4 from/to forgerock-community-repository (https://maven.forgerock.org/repo/community): status code: 401, reason phrase:  (401)
```
According to https://backstage.forgerock.com/knowledge/kb/article/a53108595, ForgeRock URL changed from https://maven.forgerock.org/repo/ to https://maven.forgerock.org/artifactory/.
This pull request updates the pom.xml to use thes new URL.
> Use new ForgeRock repository URL

- pom.xml
The version range was: `[9,11[`  leading to activation of `jdk9` profile when running on Java 11. This can be confirmed by running: `mvn help:active-profiles`. Actually `[9,11[` is not a valid range definition according to https://maven.apache.org/ref/3.9.5/maven-artifact/apidocs/org/apache/maven/artifact/versioning/VersionRange.html#createFromVersionSpec(java.lang.String) This change update the definition of version range to `[9,11)` that actually exclude Java 11 (`jdk11` will be activated in such situation).
> Fix the JDK version range for jdk9 profile

- src/main/java/org/lsc/utils/directory/AD.java
Simple patch to manage AD unicodePwd encoding issue
This also requires to set unicodePwd as binary attribute in the LDAP connection
> Return unicodePwd as byte[] instead of String

- pom.xml
- src/install/install.xml
This fixes an issue when building with Java 14+
See https://openjdk.org/jeps/367
For whatever reason, `@{project.url}` is not expanded in ` src/install/install.xml]`, so it's commented out, but this needs to be fixed before this can be commited.
> Update izpack to 5.2.1

- src/install/debian/lsc.postinst
- src/install/debian/rules
> Don't modify the files in postinst but rather at the build step in deb package (#273)

- src/main/java/org/lsc/jndi/PullableJndiSrcService.java
We found that LSC syncs were spamming our services and explored governing the ```lastSuccessfulSync``` using the ```PullableJndiSrcService``` and that helped us to reduce the spam on service restarts. At a high-level, this is what we do:
- Maintain a copy of the lastSuccessfulSync from LSC on Service Shutdown as a configuration in our DB
- On the restart, the first thing to do would be pull the saved lastSuccessfulSync and set it back using the setter
- This happens just before the synchorizer kicks in 
Rough Use of this approach illustrated below:
```
final IService service = synchronize.getTask(PersonnelLdapSyncConfiguration.SYNC_TASK_NAME).getSourceService();
if(service instanceof PullableJndiSrcService) {
PullableJndiSrcService srcService = (PullableJndiSrcService) service; …
```
> Added setters & getters for lastSuccessfulSync

- src/install/debian/rules
- src/install/etc/default/lsc-async
- src/install/etc/default/lsc-sync
- src/install/lib/systemd/system/lsc-async.service
- src/install/lib/systemd/system/lsc-async@.service
- src/install/lib/systemd/system/lsc-sync@.timer
- src/install/lsc.spec
- src/main/assembly/dist.xml
@davidcoutadeur This should polish up the systemd work we started quite some time ago.
> Fix lsc-async unitfile and a bit more

- pom.xml
- src/main/java/org/lsc/AbstractSynchronize.java
- src/main/java/org/lsc/jndi/AbstractSimpleJndiService.java
- src/main/java/org/lsc/jndi/JndiServices.java
- src/main/java/org/lsc/jndi/ScriptableJndiServices.java
- src/main/java/org/lsc/service/AbstractJdbcService.java
- src/main/java/org/lsc/service/MultipleDstService.java
- src/main/java/org/lsc/service/XALdifDstService.java
- src/main/java/org/lsc/utils/RhinoDebugger.java
- src/main/java/org/lsc/utils/SetUtils.java
> #161 - Fixing javadoc to remove WARNING

- src/main/java/org/lsc/utils/ScriptingEvaluator.java
- avoid NullPointerException even if rhino and js are missing
> fallback to rhino if no default javascript is found .3 (lscproject#280)

- src/main/java/org/lsc/jndi/JndiServices.java
> Fixed bug override globally configured pageSize variable in the middle of the code

- sample/hsqldb/bin/lsc-sample
Should fix issue from https://mail.ow2.org/wws/arc/lsc-users/2025-01/msg00008.html
>When I was trying to run 'bin/lsc-sample --import sample.csv' to import the CSV, I got this error:
```
s: Caretakers/lsc/lsc-2.1.6/sample/hsqldb/bin/../../../lib/hsqldb*.jar: No such file or directory
bin/lsc-sample: line 186: cd: /Users/jon/Documents/Commons: No such file or directory
Error: Unable to access jarfile
```
>The issue is that one of the folders had a space in the name, which caused the error. Once I replaced the space with an underscore, everything was fine.
> SAMPLE_HOME can contain spaces

- etc/lsc.xml-sample
The goal is to have a default lsc.xml that is easy to understand.
Here I choose to have a simple task to synchronize users between 2 LDAP directories, with some interesting features of LSC:
* Have a different pivot attribute between source and destination (uid/sAMAccountName)
* Escape RDN value
* Force objectClass values (top/user)
* Set a static value in an attribute (description)
* Map attributes (uid/sAMAccountName)
* Automatically synchronize attributes (cn, givenName, mail, sn)
> Provide a cleaner lsc.xml sample file

- pom.xml
> fix error of izpack-maven-plugin for recent versions of openjdk 21 (#384)

- src/install/debian/rules
Back to .xz to support older Debian versions
> Force compression alg for Debian package
